### ISSUE TITLE
Create new pool (without cloning one)

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#29]
It would be nice to have in the pool-manager a button, where you can create your own pool, without cloning it from existing one. So one can create independet pools.

**Comment by carrotIndustries** [comment]
Since that's against my idea about how the pool is supposed to work, I won't provide UI for creating new pools. If someone still want's to so, he/she will have to figure it out. Other projects such as openstreetmap and wikipedia have shown that a centralized-data approach works well. Making it too easy to create a new pool may lead to fragmentation.
