### ISSUE TITLE
New logo?

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#57]
I'd propose the idea of a new logo for the program, as it advanches so fast, a new logo would look more professional. I was playing with logo maker for a minute, and they seem to have good logos to offer (as far as i see for free...)
![grafik](https://user-images.githubusercontent.com/17407241/34608508-ee660e12-f218-11e7-9575-95f94cef1813.png)
https://www.logomaker.com/

Of cause, it will not be as good as a designed one, however, i think for the moment it would look quite nice...
  

**This logo is just a very very quick idea**

**Comment by carrotIndustries** [comment]
Thanks for the effort, but no. In case any designer reads along, the current 80s-themed logo is approximately what I'd like to have. Some more inspiration: https://www.google.de/search?tbm=isch&q=80s+math+book+cover&chips=q:80s+math+book+cover,online_chips:vaporwave

**Comment by atoav** [comment]
I happen to be a graphic designer and want to offer myself to create a nice logo for horizon.
Logos typically are a very subjective topic, but I think one can boil down a few objective aspects ( considering a icon for a open source project):

1. a logo should fit the project (or its name)
2. a logo should offer a distinctive and harmonic color to make it recognizeable
3. a icon should work especially well at both big and small sizes
4. a icon should work on bright and black backgrounds alike

From point 3 rationally follows, that the icons complexity has to be low enough to yield a working icon at a small size. This is especially true for the current icon. 

I made a single draft – for paying customers I'd typically do more than one but I don't know wether this is even wanted here. I kinda liked to contribute, because of all the open source EDA projects horizon looks most promising to me.  Typically I'd start out with a black and white shape version and start tuning in colors later. The small icons will be drawn pixel by pixel to maximize small scale readability.  Obviously I'd need to be sure that a certain draft is to be taken, to avoid loops and unecessary work.  

In this draft I tried to catch the horizion name, like you did in your original icon, while simplyfing it and still keeping some 80s spirit alive (I hope it survived : ). Note that the different backgrounds are just for display purposes. 

![black_on_bright_bg_1920px](https://user-images.githubusercontent.com/6620266/35535886-544ce9be-0545-11e8-9cd4-7743d883bcfd.png)
![black_on_dark_bg_1920px](https://user-images.githubusercontent.com/6620266/35535887-5464932a-0545-11e8-94c0-f6cc061fa9ee.png)
![gradient_on_bright_bg_1920px](https://user-images.githubusercontent.com/6620266/35535888-547fa8cc-0545-11e8-96ae-c9053529df31.png)
![gradient_on_dark_bg_1920px](https://user-images.githubusercontent.com/6620266/35535889-5498476a-0545-11e8-8a2e-a21530ec54de.png)
![white_on_dark_bg_1920px](https://user-images.githubusercontent.com/6620266/35535890-54b13d10-0545-11e8-9bfd-57e80fe01ad4.png)

Feel free to critique etc.

**Comment by carrotIndustries** [comment]
Awesome! Nice to have something different than the usual variation of the "Board/Schematic/Gate/IC with or without pen" theme.

**Comment by atoav** [comment]
I'll play around with it for a bit and report back if anything better comes up. Any preferences on the colours?

**Comment by atoav** [comment]
I made two new monochrome versions, that sort of build up on the old draft. Both try to be a bit more distinctive, than the more generic looking drafts from yesterday. I tried to keep the horizon metaphor, but extend it with a "planetary" aspect. After all, electronics are the most powerful thing we as humanity ever came up with.  

At the same time this draft is abstract enough to be literally everything else. It could be a single pad on a PCB looked at from above or a swimming pool seen from the top of a tall building.  

| Variant | Image |
| -------- |:-------:|
| Black Sun (1080px) | ![black_sun_1080px](https://user-images.githubusercontent.com/6620266/35594227-a838ac02-0612-11e8-8f54-77769ff82233.png) |
| Black Sun (64px) | ![black_sun_64px](https://user-images.githubusercontent.com/6620266/35594230-a885aab6-0612-11e8-9247-f4eb1b067d82.png) |
| White Moon (1080px) | ![white_moon_1080px](https://user-images.githubusercontent.com/6620266/35594229-a86b8e88-0612-11e8-953e-aab9ebc9e8b0.png) |
| White Moon (64px) | ![white_moon_64px](https://user-images.githubusercontent.com/6620266/35594228-a8534c4c-0612-11e8-8b9b-2b82a6b60b9e.png) |

**Comment by carrotIndustries** [comment]
Mind that the logo will end up as 16x16px icon in the the top left of the application window as in https://raw.githubusercontent.com/wiki/carrotIndustries/horizon/images/pool-mgr.png and probably people's task bars/panels. To my judgment, the 'white moon' one stays the most recognizable.

In terms of colors, i like your first idea, but feel free to experiment.

**Comment by greenscreenflicker** [comment]
@atoav @carrotIndustries For me the moon logo looks just amazing. I love it. I think it's special and makes it recognizable.

I played a little bit with some colors, I would like. I must denote, I'm everything else then a designer, so it's just a rough idea.
![grafik](https://user-images.githubusercontent.com/17407241/35907730-14786664-0bef-11e8-8acd-4499b0358f6d.png)

**Comment by atoav** [comment]
I'd avoid gradients for well defined multiple colors. I changed the spacing between the lines on the white_moon draft a little bit and added colors. While playing around with some sunset variation I thought: "Hey – who says that it is a horizon seen on earth?" So I imagined the circle as a pale blue dot. Well.
| Variant | Image |
|:-------:|:--------:|
| Pale Blue Dot Mars (1080px) | ![pale_blue_1080px](https://user-images.githubusercontent.com/6620266/36065425-dc8c6800-0e9a-11e8-8ad1-27e24ef52e8b.png) |
| Pale Blue Dot Mars (16px) | ![pale_blue_16px](https://user-images.githubusercontent.com/6620266/36065426-e479a4ba-0e9a-11e8-8986-2d41b5808afe.png) |  

I kinda like how the small Icon still stays recognizable, the colors represent Mars but could give it a little to much 70s feel...  

So I tried another variant for the moon:  
| Variant | Image |
|:-------:|:--------:|
| Pale Blue Dot Moon (1080px) | ![pale_blue_moon_1080px](https://user-images.githubusercontent.com/6620266/36065461-811769ec-0e9b-11e8-8032-72e86680e37f.png) |
| Pale Blue Dot Moon (16px) | ![pale_blue_moon_16px](https://user-images.githubusercontent.com/6620266/36065465-9734af00-0e9b-11e8-8882-3a1805ab623f.png) |  
Despite the lack of recognizable hue in the "landscape" part of things, I think this draft still stays very recognizable at small sizes, color-wise. For the sacrifice in color we get a little more serious professionalism.  

What do you think?

**Comment by carrotIndustries** [comment]
Great work! 

> What do you think?

The not-so-much colored one indeed looks more professional, let's stick with that one.

**Comment by atoav** [comment]
I created a repo called [horizon-logo](https://github.com/atoav/horizon-logo) with all possible source formats and exports. The PNGs with the resolutions 16px, 32px and 64px have been made pixel perfect and should look decent at small sizes now. Feel free to use it within horizon.

**Comment by carrotIndustries** [comment]
b805a35ad5b55b384da64fccf31c9f24d9c32016 adds the new icons

**Comment by greenscreenflicker** [comment]
Looks amazing! @atoav good work. However, i see there some artefacts, the circle is not round.
![grafik](https://user-images.githubusercontent.com/17407241/36095722-a917c91a-0ff3-11e8-93f5-2e8063811cbf.png)

**Comment by atoav** [comment]
Interesting over here it looks like this with a small taskbar:  
![2018-02-12 14_49_35-horizon pool manager](https://user-images.githubusercontent.com/6620266/36099787-2ffe8832-1004-11e8-8587-788f4e65d835.png)  

and with a big Taskbar:  
![2018-02-12 14_50_07-horizon pool managerbig](https://user-images.githubusercontent.com/6620266/36099794-3b253b0c-1004-11e8-9a38-e5aa43de46db.png)  

As you can see I don't have such scaling artifacts and they are certainly not in the images themselves. I don't know how the Windows Taskbar handles Icon scaling and if there are any ways to optimize it (from the position of a graphic designer)
