### ISSUE TITLE
Package editor: Add rotating option to step files

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#61]
![grafik](https://user-images.githubusercontent.com/17407241/34877226-82604b50-f7a5-11e7-9038-c17d42932e12.png)
Option like, x,y,z offset and rotation required for using step models.

By the way: Where should the step models be saved?

**Comment by carrotIndustries** [comment]
I didn't add such an option since specifying offset/rotation by typing in a number isn't exactly the way it should be done. To me, there are primarily two sources of 3D Models:
 - The Kicad 3D models library at https://github.com/KiCad/kicad-packages3D/
 - 3D models provided by vendors

The kicad 3d models already have the canonical zero orientation, so there's no need to rotate these. Models provided by vendors are usually all over the place requiring reorientation with a proper MCAD tool such as FreeCAD.

See the existing 3d models for guidance on where to put the files.

**Comment by greenscreenflicker** [comment]
@carrotIndustries : It seems, like the 3d models are not copied by cloning the pool.  Maybe you can fix this?

@carrotIndustries: I will try to use kicad packages as first resource. The database seems quite good to me.

**Comment by carrotIndustries** [comment]
Yeah, integration with the download/upgrade things in the pool manager is still WIP.

**Comment by carrotIndustries** [comment]
since 2953d2f8669ff40b25e23bc0326fe11341a6be43 the pool manager handle 3d models in download and upgrade

**Comment by greenscreenflicker** [comment]
@carrotIndustries There is some commenting on this issue on Mikrocontroller.net
https://www.mikrocontroller.net/topic/417908#5282789
