### ISSUE TITLE
Package editor: Infinite loop when deleting a package. (Kind of Crash)

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#62]
When deleting a package in package editor the current version 72afa3e there seems to be an infinite loop; the program does not terminate.

**Comment by greenscreenflicker** [comment]
There was an alternative package for it defined (the one i was deleting), maybe this is a hint.

**Comment by greenscreenflicker** [comment]
Ok, found a manual solution: Setting "alternate_for": "[uid]", setting it to nothing solves it.
So maybe the delete function should check if the package deleted is defined as an alternative package, and if yes, remove that tag. 
The update function should not while(1) if a tag cannot be found.

**Comment by carrotIndustries** [comment]
The issue is related to the way the pool manager handles updating the packages: It repeatedly crawls the packages directory until all references are resolved. When a package can't be found, this leads to the infinite loop you're describing.

To fix this properly, the pool manger needs to figure out all dependencies beforehand, build a dependency graph and error out  if there are unresolved dependencies or cycles.
